# NOTE: KEYWORDS must be written in capslock

# KEYWORDS can be divided in KEY Events that express the type of 
# event this effect mustt be connected to.
# for example MOVE is called every time a card is moved form an area
# to another
# INTERRUPT make sure you can play that card in every moment risolving 
# that effect

# the lower case are called arguments or prerequisites, they can expand
# the event by creating more conditions
# for example let's read the white card 
# When the effect take place? when you call the function MOVE
# What is the card you need to move when you call this effect? this card
# From where you need to move the card? from the player hand
# Where you need to move the card? to the player battlefield
# What happen when all those conditions are true? you call the function 
# DRAW with the argument 1



[Plains]
	id = '01'
	set = 'LND'
	supertype = 'basic'
	type = 'land'
	subtype = 'plains'
	effects = ['MOVE _card this _from hand _to battlefield: DRAW 1']

[Island]
	id = '02'
	set = 'LND'
	supertype = 'basic'
	type = 'land'
	subtype = 'island'
	effects = ['MOVE _card this _from hand _to battlefield: LOOK 1',
						'INTERRUPT: NEGATE']

[Swamp]
	id = '03'
	set = 'LND'
	supertype = 'basic'
	type = 'land'
	subtype = 'swamp'
# TODO: implement effect remember to use pipes to keep shit modular
	effects = ['MOVE _card this _from hand _to battlefield:  CHOOSE 3 opponent hand | CHOOSE 1 player | DISCARD 1']

[Mountain]
	id = '04'
	set = 'LND'
	supertype = 'basic'
	type = 'land'
	subtype = 'moutain'
	effects = ['MOVE _card this _from hand _to battlefield: DESTROY 1']

[Forest]
	id = '05'
	set = 'LND'
	supertype = 'basic'
	type = 'land'
	subtype = 'forset'
	effects = ['MOVE _card this _from hand _to battlefield: REVIVE 1']

	# NOTE: add possibility to script in lua inside the toml
	# effect = ['this enter battlefield_player from hand_player: function() end']
